### ISSUE TITLE
[1.12.x] Sweep attack bar is not shown

### ISSUE THREAD

**Issue by Gentle888** [crazysnailboy/AdvancedHUD#4]

**Comment by crazysnailboy** [comment]
Can I have a bit more information on this please? Do you mean the attack indicator? It renders fine for me, either below the crosshair or next to the hotbar (configurable through Minecraft's video options).

Can you check to see if it works without the other HUD mods you have installed, and if so can you try and work out which mod is causing the conflict?

**Comment by crazysnailboy** [comment]
Any updates on this?

**Comment by Gentle888** [comment]
Attack indicator were off. Excuse me for my stupidiness. '*.*
